# Generated by Django 4.0.4 on 2022-07-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('package', models.CharField(choices=[('package1', 'package2'), ('package2', 'package2'), ('package3', 'package3'), ('package4', 'package4'), ('package5', 'package5')], max_length=200, null=True)),
                ('pay_gateway', models.CharField(choices=[('paypal', 'paypal'), ('creditCard', 'creditCard')], max_length=200, null=True)),
            ],
        ),
    ]
