# Generated by Django 4.0.4 on 2022-07-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
                ('feature1', models.CharField(max_length=200, null=True)),
                ('feature2', models.CharField(max_length=200, null=True)),
                ('feature3', models.CharField(max_length=200, null=True)),
                ('feature4', models.CharField(max_length=200, null=True)),
                ('feature5', models.CharField(max_length=200, null=True)),
                ('feature6', models.CharField(max_length=200, null=True)),
                ('feature7', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
