# Generated by Django 4.0.4 on 2022-07-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitalapp', '0003_alter_order_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='package',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
